(****************************************************************************
 *
 *            WinLIRC plug-in for jetAudio
 *
 *            Copyright (c) 2016 Tim De Baets
 *
 ****************************************************************************
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ****************************************************************************
 *
 * jetAudio API constant declarations
 *
 ****************************************************************************)

unit JetAudio6_Const;
{**************************************************************************}
{                                                                          }
{    This C DLL header file first (automatic) conversion generated by:     }
{    HeadConv 4.0 (c) 2000 by Bob Swart (aka Dr.Bob - www.drbob42.com)     }
{      Final Delphi-Jedi (Darth) command-line units edition                }
{                                                                          }
{    Generated Date: 18/04/2009                                            }
{    Generated Time:  0:08:11                                              }
{                                                                          }
{**************************************************************************}

interface

uses
{$IFDEF WIN32}
  Windows, Messages;
{$ELSE}
  Wintypes, WinProcs;
{$ENDIF}


{=> jetaudio7_pluginsdk\CONST.H <=}

{ #pragma once }

type
  eRepeatMode = (
    REPEAT_NONE, 
    REPEAT_THIS, 
    REPEAT_ALL  );

type
  eRandomMode = (
    RANDOM_NORMAL, 
    RANDOM_RANDOM, 
    RANDOM_PROGRAM  );

type
  eMediaMode = (
    MEDIAMODE_DISC, 
    MEDIAMODE_ACD, 
    MEDIAMODE_VCD, 
    MEDIAMODE_DVD, 
    MEDIAMODE_FILE  );

type
  eCDPlayMode = (
    CDPLAY_ANALOG, 
    CDPLAY_DIGITAL  );

type
  eTimeMode = (
    TIMEMODE_ELAPSED, 
    TIMEMODE_REMAINED  );

type
  eInfoDisplay = (
    INFODISP_ARTIST_TITLE, 
    INFODISP_ALBUM_YEAR, 
    INFODISP_FILENAME, 
    INFODISP_COMMENT, 
    INFODISP_COPYRIGHT  );

type
  eSlideMode = (
    SLIDEMODE_NONE, 
    SLIDEMODE_TOP, 
    SLIDEMODE_RIGHT, 
    SLIDEMODE_BOTTOM, 
    SLIDEMODE_LEFT  );

type
  eOSDMethod = (
    OSD_NONE, 
    OSD_ALWAYS, 
    OSD_FIRST  );

type
  eSortFlag = (
    SORT_FLAG_TITLE, 
    SORT_FLAG_ARTIST, 
    SORT_FLAG_ALBUM_TITLE, 
    SORT_FLAG_GENRE, 
    SORT_FLAG_YEAR, 
    SORT_FLAG_DESCRIPTION, 
    SORT_FLAG_TRACK, 
    SORT_FLAG_FILENAME, 
    SORT_FLAG_DIRECTORY, 
    SORT_FLAG_EXTENSION, 
    SORT_FLAG_FILETIME_WR, 
    SORT_FLAG_FILETIME_CT, 
    SORT_FLAG_FILESIZE,
    SORT_FLAG_ADDEDTIME,
    SORT_FLAG_PLAYEDTIME,
    SORT_FLAG_RATING,
    SORT_FLAG_PLAYEDCOUNT_TOTAL,
    SORT_FLAG_PLAYEDCOUNT_TODAY,
    SORT_FLAG_PLAYEDCOUNT_WEEK,
    SORT_FLAG_PLAYEDCOUNT_1_MONTH,
    SORT_FLAG_TEMPO,
    SORT_FLAG_SITUATION,
    SORT_FLAG_CATEGORY,
    SORT_FLAG_BITRATE );
  eWheelAction = (
    WHEELACTION_NOTHING, 
    WHEELACTION_FORWARD, 
    WHEELACTION_SKIPTRACK, 
    WHEELACTION_VOLUME, 
    WHEELACTION_QUICKTRACKSCROLL, 
    WHEELACTION_SPEED, 
    WHEELACTION_VIDEO_BRIGHTNESS, 
    WHEELACTION_VIDEO_CONTRAST, 
    WHEELACTION_SUBTITLE_POSITION, 
    WHEELACTION_SUBTITLE_SIZE, 
    WHEELACTION_LAST  );
{-enum eXButtonAction }
{-{ }
{-XBUTTONACTION_NOTHING, XBUTTONACTION_FORWARD, XBUTTONACTION_SKIPTRACK, }
{-XBUTTONACTION_VOLUME, XBUTTONACTION_QUICKTRACKSCROLL, XBUTTONACTION_SPEED, }
{-XBUTTONACTION_LAST }
{-; }
{= }

const
  MAX_LYRICSEARCH_OPTION = (5);
type
  eLyricSearchOption = (
    LYRICSEARCH_FILE, 
    LYRICSEARCH_TAG_UNSYNC, 
    LYRICSEARCH_TAG_SYNC, 
    LYRICSEARCH_INTERNET_CIX, 
    LYRICSEARCH_INTERNET_LEO  );

type
  eScreenMode = (
    SCREENMODE_NORMAL, 
    SCREENMODE_NORMAL_CURRENT, 
    SCREENMODE_NORMAL_50, 
    SCREENMODE_NORMAL_80, 
    SCREENMODE_NORMAL_150, 
    SCREENMODE_NORMAL_200, 
    SCREENMODE_FULL_NORMAL, 
    SCREENMODE_FULL_WIDTH, 
    SCREENMODE_FULL_HEIGHT  );

type
  eAspectMode = (
    ASPECTMODE_ORG, 
    ASPECTMODE_4X3, 
    ASPECTMODE_16X9, 
    ASPECTMODE_185X100, 
    ASPECTMODE_235X100  );

const
  MENU_OFFSET_HISTORY_START = (44600);
const
  MENU_OFFSET_HISTORY_END = (44699);
const
  MENU_OFFSET_BOOKMARK_START = (44700);
const
  MENU_OFFSET_BOOKMARK_END = (44799);
const
  MENU_OFFSET_EFFECTOR_START = (44800);
const
  MENU_OFFSET_EFFECTOR_END = (44899);
const
  MENU_OFFSET_DRIVE_START = (44900);
const
  MENU_OFFSET_DRIVE_END = (44999);
const
  MENU_OFFSET_ALBUM_START = (45000);
const
  MENU_OFFSET_ALBUM_END = (49999);
const
  MENU_OFFSET_TRACK_START = (50000);
const
  MENU_OFFSET_TRACK_END = (65000);

{/// EQ Constants }
const
  MAX_FREQ_BAND = (20);
const
  MAX_PANEL_EQ_MODE = (7);
const
  MAX_PRESET_EQ_MODE = (14);
const
  MIN_USER_EQ_MODE = (MAX_PRESET_EQ_MODE);
const
  MAX_USER_EQ_MODE = (MIN_USER_EQ_MODE+1);

type
  eEQMode = (
    EQMODE_ROCK, 
    EQMODE_POP, 
    EQMODE_JAZZ, 
    EQMODE_CLASSIC, 
    EQMODE_VOCAL, 
    EQMODE_FLAT1, 
    EQMODE_USER1, 
    EQMODE_DANCE, 
    EQMODE_HEADPHONE, 
    EQMODE_BALLAD, 
    EQMODE_RAP, 
    EQMODE_HEAVYMETAL, 
    EQMODE_FLAT2, 
    EQMODE_USER2  );

type
  eOSDUpdate = (
    OSD_UPDATE_TIME{=1}, 
    OSD_UPDATE_VOLUME, 
    OSD_UPDATE_MUTE, 
    OSD_UPDATE_SPEED, 
    OSD_UPDATE_BUFFERING, 
    OSD_UPDATE_INDEXING, 
    OSD_UPDATE_SEARCHING, 
    OSD_UPDATE_COLOR_BRIGHTNESS{=10}, 
    OSD_UPDATE_COLOR_CONTRAST, 
    OSD_UPDATE_COLOR_HUE, 
    OSD_UPDATE_COLOR_SATURATION, 
    OSD_UPDATE_COLOR_GAMMA,
    OSD_UPDATE_COLOR_RESET,
    OSD_UPDATE_AUDIO{=20},
    OSD_UPDATE_ANGLE,
    OSD_UPDATE_SUBTITLE_LANG{=30},
    OSD_UPDATE_SUBTITLE_TIMING,
    OSD_UPDATE_SUBTITLE_SIZE,
    OSD_UPDATE_FULLSCREEN_MODE{=40},
    OSD_UPDATE_FULLSCREEN_ASPECT,
    OSD_UPDATE_FULLSCREEN_ZOOM,
    OSD_UPDATE_FULLSCREEN_MOVE  );
    {///////////////////////////////////////////////////////////////////////////  );
{/// OpenAction constants }
type
  eFileOpenAction = (
    FOA_CLEAR_DEFAULT, 
    FOA_ADD_TO_DEFAULT, 
    FOA_ADD_TO_CURRENT  );

const
  FOP_DONT_PLAY = ($0001);
{/////////////////////////////////////////////////////////////////////////// }

{/// MSG Constants }
const
  WM_VIDEOWND_SIZE_CHANGED = (WM_APP+900);
const
  WM_VIDEOWND_INPUT_ENTERED = (WM_APP+901);

const
  WM_PLAY_TITLE = (WM_APP+920);
const
  WM_PLAY_CHAPTER = (WM_APP+921);
const
  WM_LOAD_ALBUM = (WM_APP+922);
const
  WM_LOAD_DRIVE = (WM_APP+923);
const
  WM_OPEN_FILE = (WM_APP+924);

const
  WM_TRACK_ADD = (WM_APP+930);
const
  WM_TRACK_REMOVE = (WM_APP+931);
const
  WM_TRACK_TAG_EDIT = (WM_APP+932);
const
  WM_TRACK_EDIT = (WM_APP+933);

const
  WM_SPEED_CHANGE = (WM_APP+940);

const
  WM_SKIN_LOAD = (WM_APP+950);
const
  WM_DO_FUNC = (WM_APP+951);

const
  WM_GET_VOLUME = (WM_APP+930);
const
  WM_SET_VOLUME = (WM_APP+931);

{/// Index of IDB_MENU_GENERAL }
const
  IDB_IDX_ALBUM = (0);
const
  IDB_IDX_ARTIST = (1);
const
  IDB_IDX_TRACK = (2);
const
  IDB_IDX_DRIVE = (3);
const
  IDB_IDX_SOUNDCARD = (4);
const
  IDB_IDX_LOAD = (5);
const
  IDB_IDX_SAVE = (6);
const
  IDB_IDX_TIME_ELAPSED = (7);
const
  IDB_IDX_TIME_REMAINED = (8);
const
  IDB_IDX_ANALOG = (9);
const
  IDB_IDX_DIGITAL = (10);
const
  IDB_IDX_ADD = (11);
const
  IDB_IDX_TOOL = (12);
const
  IDB_IDX_SOUNDEFFECT = (13);
const
  IDB_IDX_EQ = (14);
const
  IDB_IDX_BASIC_CONTROL = (15);
const
  IDB_IDX_SPECIAL_CONTROL = (16);
const
  IDB_IDX_REPEAT = (17);
const
  IDB_IDX_RANDOM = (18);
const
  IDB_IDX_FULLSCREEN_ADJUST = (19);
const
  IDB_IDX_SCREEN_SIZE = (20);
const
  IDB_IDX_IMPORT = (21);
const
  IDB_IDX_EXPORT = (22);
const
  IDB_IDX_ALBUM_MEDIA = (23);
const
  IDB_IDX_ALBUM_PLAYLIST = (24);
const
  IDB_IDX_ALBUM_AUTO_PLAYLIST = (25);
const
  IDB_IDX_ALBUM_SEARCH = (26);
const
  IDB_IDX_ALBUM_RADIO = (27);
const
  IDB_IDX_NEW_ALBUM = (28);
const
  IDB_IDX_SUBTITLE = (29);
const
  IDB_IDX_ASPECT_RATIO = (30);
const
  IDB_IDX_AUDIO = (31);
const
  IDB_IDX_FILTER_PROPERTIES = (32);
const
  IDB_IDX_EDGE = (33);
const
  IDB_IDX_MONITOR = (34);
const
  IDB_IDX_TOOLBAR = (35);
const
  IDB_IDX_SEARCH = (36);
const
  IDB_IDX_MUSICSTORE = (37);
const
  IDB_IDX_BOOKMARK_ADD = (38);
const
  IDB_IDX_BOOKMARK_REMOVE = (39);
const
  IDB_IDX_HISTORY = (40);
const
  IDB_IDX_THUMBNAIL = (41);
const
  IDB_IDX_COLUMN = (42);
const
  IDB_IDX_EDIT = (43);
const
  IDB_IDX_SORT = (44);
const
  IDB_IDX_FILE_COPY = (45);

{/// Index of IDB_ATTR_ALBUM }
const
  IMAGE_ALBUM_CD_ROOT = (0);
const
  IMAGE_ALBUM_MEDIA_ROOT = (1);
const
  IMAGE_ALBUM_DRIVE_ROOT = (2);
const
  IMAGE_ALBUM_BROWSE_ROOT = (3);
const
  IMAGE_ALBUM_SEARCH_ROOT = (4);
const
  IMAGE_ALBUM_RADIO_ROOT = (5);
const
  IMAGE_ALBUM_PLAYLIST_ROOT = (6);
const
  IMAGE_ALBUM_AUTO_PLAYLIST_ROOT = (7);
const
  IMAGE_ALBUM_MUSIC_STORE_ROOT = (8);
const
  IMAGE_ALBUM_BROWSE_RATING = (9);
const
  IMAGE_ALBUM_BROWSE_ALBUM = (10);
const
  IMAGE_ALBUM_BROWSE_ARTIST = (11);
const
  IMAGE_ALBUM_BROWSE_GENRE = (12);
const
  IMAGE_ALBUM_BROWSE_TEMPO = (13);
const
  IMAGE_ALBUM_BROWSE_CATEGORY = (14);
const
  IMAGE_ALBUM_BROWSE_SITUATION = (15);
const
  IMAGE_ALBUM_BROWSE_ALL_MUSIC = (16);
const
  IMAGE_ALBUM_BROWSE_ALL_VIDEO = (17);
const
  IMAGE_ALBUM_BROWSE_ALL_MEDIA = (18);
const
  IMAGE_ALBUM_CD_ALBUM = (19);
const
  IMAGE_ALBUM_MEDIA_ALBUM = (20);
const
  IMAGE_ALBUM_MEDIA_ALBUM_LINKED = (21);
const
  IMAGE_ALBUM_RADIO_ALBUM = (22);
const
  IMAGE_ALBUM_MUSIC_STORE_ALBUM = (23);
const
  IMAGE_ALBUM_CD_TRACK = (24);
const
  IMAGE_ALBUM_AUDIO_TRACK = (25);
const
  IMAGE_ALBUM_CD_PROG_TRACK = (26);
const
  IMAGE_ALBUM_AUDIO_PROG_TRACK = (27);
const
  IMAGE_ALBUM_PLAYLIST = (28);
const
  IMAGE_ALBUM_AUTO_PLAYLIST = (29);
const
  IMAGE_ALBUM_RADIO_TRACK = (30);
const
  IMAGE_ALBUM_RADIO_PROG_TRACK = (31);
const
  IMAGE_ALBUM_VIDEO_TRACK = (32);
const
  IMAGE_ALBUM_VIDEO_PROG_TRACK = (33);
const
  IMAGE_ALBUM_CURRENT_TRACK = (34);
const
  IMAGE_ALBUM_STAR_NORMAL = (35);
const
  IMAGE_ALBUM_STAR_EMPTY = (36);
const
  IMAGE_ALBUM_STAR_DOT = (37);
const
  IMAGE_ALBUM_MUSIC_LINK_ALBUM = (38);
const
  IMAGE_ALBUM_MUSIC_LINK_ROOT = (39);



type
  eAlbumType = (
    CMP_NONE{=0}, 
    CMP_AUDIOCD{=2}, 
    CMP_MEDIA, 
    CMP_OLD_MIDI, 
    CMP_OLD_DGV, 
    CMP_ROOT_AUDIOCD{=100}, 
    CMP_ROOT2_DRIVE, 
    CMP_ROOT2_AUDIOCD_GENRE, 
    CMP_ROOT2_AUDIOCD_ARTIST, 
    CMP_ROOT_MEDIA{=200}, 
    CMP_ROOT2_MEDIA_GENRE, 
    CMP_ROOT2_MEDIA_ARTIST, 
    CMP_ROOT_PLAYLIST{=300}, 
    CMP_PLAYLIST, 
    CMP_ROOT_AUTO_PLAYLIST{=400}, 
    CMP_AUTO_PLAYLIST, 
    CMP_ROOT_BROWSE{=500}, 
    CMP_ROOT2_BROWSE_ALL, 
    CMP_ROOT2_BROWSE_ARTIST, 
    CMP_ROOT2_BROWSE_ALBUM, 
    CMP_ROOT2_BROWSE_GENRE, 
    CMP_ROOT2_BROWSE_RATING, 
    CMP_ROOT2_BROWSE_TEMPO, 
    CMP_ROOT2_BROWSE_CATEGORY, 
    CMP_ROOT2_BROWSE_SITUATION, 
    CMP_BROWSE_ARTIST{=550}, 
    CMP_BROWSE_ALBUM, 
    CMP_BROWSE_GENRE, 
    CMP_BROWSE_RATING, 
    CMP_BROWSE_TEMPO, 
    CMP_BROWSE_CATEGORY, 
    CMP_BROWSE_SITUATION, 
    CMP_BROWSE_FILES, 
    CMP_SEARCH{=600}, 
    CMP_ROOT_RADIO{=700}, 
    CMP_ROOT2_RADIO_LANGUAGE, 
    CMP_ROOT3_RADIO_GENRE, 
    CMP_ROOT_CONTENTS{=800}, 
    CMP_ROOT2_MUSIC_STORE, 
    CMP_MUSIC_STORE_LINK, 
    CMP_MUSIC_LYRIC_LINK, 
    CMP_ROOT_MUSIC_CENTER{=900}, 
    CMP_MUSIC_RANK_LINK );

const
  FILEEXT_MUSIC = '.wav.mp3;.mp2;.wma;.ogg;.flac;.mpc;.ape;.mid;.midi;.rmi;.m4a;.ra;.ram;.aac;.kar;.tta;.spx;.wv;';
const
  FILEEXT_VIDEO = '.avi.asf;.wmv;.mpeg;.mpg;.mpe;.m1v;.m2v;.dat;.vob;.mp4;.ogm;.mkv;.qt;.mov;.rm;.rmvb;.3gp;.3g2;.k3g;.m4v;.dvr-ms;.ts;.tp;.trp;.flv;';
const
  FILEEXT_VIDEO_PMP = '.asf.avi;.wmv;.mpeg;.mpg;.mpe;';
const
  FILEEXT_PHOTO = '.bmp.jpg;.jpeg;.gif;.png;.ico;.tif;.tiff;.tga;.pcx;';
const
  FILEEXT_TEXT = '.txt';
const
  FILEEXT_SUBTITLE = '.srt.sub;.smi;.psb;.ssa;.ass;.idx;.usf;.xss;.ssf;.smil;';

const
  FILEEXT_META_PIC = '.mp3.wma;.ape;.mpc;.flac;.tta;.wv;';

{/////////////////////////////////////////////////////////////////////////// }

const
  THUMB_INDEX_EMPTY = (0);
const
  THUMB_INDEX_UNKNOWN = (1);
const
  THUMB_INDEX_MUSIC = (2);
const
  THUMB_INDEX_VIDEO = (3);
const
  THUMB_INDEX_SUBTITLE = (4);
const
  THUMB_INDEX_PHOTO = (5);
const
  THUMB_INDEX_TEXT = (6);
const
  THUMB_INDEX_GAME = (7);
const
  THUMB_INDEX_FOLDER_UNKNOWN = (8);
const
  THUMB_INDEX_FOLDER_MUSIC = (9);
const
  THUMB_INDEX_FOLDER_VIDEO = (10);
const
  THUMB_INDEX_FOLDER_PHOTO = (11);
const
  THUMB_INDEX_FOLDER_TEXT = (12);
const
  THUMB_INDEX_FOLDER_GAME = (13);
const
  THUMB_INDEX_SX_DEFAULT = (14);

{////////////////////////////////////////////////////////////////////////////////// }
{/// OLD DEFINITIONS !!! }
{/// }

{/// Media File Format Constants }
type
  NewExit = (
    MFF_NONE, 
    MFF_GENERAL, 
    MFF_AIF, 
    MFF_WAV, 
    MFF_SND, 
    MFF_MPA, 
    MFF_RA, 
    MFF_MID, 
    MFF_KAR, 
    MFF_IMS, 
    MFF_MOD, 
    MFF_AVI, 
    MFF_WMV, 
    MFF_MOV, 
    MFF_MPV, 
    MFF_RV, 
    MFF_AUDIOCD, 
    MFF_WMA, 
    MFF_WM_META, 
    MFF_SMI, 
    MFF_DVD  );

{////////////////////////////////////////////////////////////////////////////////// }


const
  DEF_CDDB_HOST = 'http://freedb.freedb.org';

implementation

end.
